export const SET_CATEGORY_LOADING = "SET_CATEGORY_LOADING";
export const SET_NOTE_LOADING = "SET_NOTE_LOADING";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const AUTHENTICATE = "AUTHENTICATE";

export const GET_NOTE_BY_ID = "GET_NOTE_BY_ID";
export const GET_NOTES = "GET_NOTES";
export const CREATE_NOTE = "CREATE_NOTE";
export const UPDATE_NOTE_BY_ID = "UPDATE_NOTE_BY_ID";
export const DELETE_NOTE_BY_ID = "DELETE_NOTE_BY_ID";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY_BY_ID = "UPDATE_CATEGORY_BY_ID";

export const SET_EDITING = "SET_EDITING";
export const UPDATE_EDITING_NOTE = "UPDATE_EDITING_NOTE";
