export const GET_NOTES = "GET_NOTES";
export const GET_ACTIVE_NOTE = "GET_ACTIVE_NOTE";
export const GET_ACTIVE_NOTE_ERROR = "GET_ACTIVE_NOTE_ERROR";
export const CREATE_NOTE = "CREATE_NOTE";
export const CREATE_NOTE_ERR = "CREATE_NOTE_ERR";
export const DELETE_NOTE = "DELETE_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const UPDATE_NOTE_OPTIONS = "UPDATE_NOTE_OPTIONS";
export const GET_ACTIVE_NOTE_LOCKED = "GET_ACTIVE_NOTE_LOCKED";
export const GET_SHARE_BY_ID = "GET_SHARE_BY_ID";
export const GET_SHARE_ERROR = "GET_SHARE_ERROR";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_ERR = "CREATE_CATEGORY_ERR";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_ERR = "AUTH_ERR";
export const SET_PIN_CODE = "SET_PIN_CODE";
export const SET_LOADING = "SET_LOADING";

export const ADD_MESSAGE = "SET_MESSAGE";
export const GET_MESSAGES = "GET_MESSAGES";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
