export const GET_NOTES = "GET_NOTES";
export const GET_ACTIVE_NOTE = "GET_ACTIVE_NOTE";
export const CREATE_NOTE = "CREATE_NOTE";
export const CREATE_NOTE_ERR = "CREATE_NOTE_ERR";
export const DELETE_NOTE = "DELETE_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_ERR = "CREATE_CATEGORY_ERR";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_ERR = "AUTH_ERR";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
